### PR TITLE
Fix hermione repeat error

### LINKED ISSUE #681: Allure-hermione deletes test and closes worker if test run with repeat using hermione-test-repeater
**Describe the bug**
If test run with repeat using hermione-test-repeater, allure-hermione delete test in "runningTests.delete(testId());" and worker wants to start test again, but it already deleted after first run

If we comment and disable line
```
runningTests.delete(testId());
```
in allure-hermione package - it works ok

**To Reproduce**
1. It can be reproduced in repo https://github.com/fortrest-jr/allure-tests/tree/Steps on branch Steps
2. Switch to branch Steps
3. npm i
4. npm run test -- repeat 10

**Expected behavior**
All repeats are running and we got common result

**Actual behavior**
Second repeat was failed with error 
```
Error: Can't set test metadata due browser session has been finished
    at handleAllureAttachment (/Users/alenanikonova/tests/allure-tests/node_modules/allure-hermione/dist/index.js:53:19)
    at ChildProcess.<anonymous> (/Users/alenanikonova/tests/allure-tests/node_modules/allure-hermione/dist/index.js:151:17)
    at ChildProcess.emit (node:events:402:35)
    at ChildProcess.emit (node:domain:475:12)
    at emit (node:internal/child_process:917:12)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
i111351658:allure-tests alenanikonova$ WARN: Failed to take screenshot on test fail: Error: Can't open file for writing
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at new NodeError (node:internal/errors:371:5)
    at process.target.send (node:internal/child_process:721:16)
    at Object.emit (/Users/alenanikonova/tests/allure-tests/node_modules/hermione/lib/utils/ipc.js:6:41)
    at BrowserPool.freeBrowser (/Users/alenanikonova/tests/allure-tests/node_modules/hermione/lib/worker/runner/browser-pool.js:57:13)
    at BrowserAgent.freeBrowser (/Users/alenanikonova/tests/allure-tests/node_modules/hermione/lib/worker/runner/browser-agent.js:26:20)
    at TestRunner.run (/Users/alenanikonova/tests/allure-tests/node_modules/hermione/lib/worker/runner/test-runner/index.js:83:28)
Emitted 'error' event on process instance at:
    at node:internal/child_process:725:35
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

### PR DESCRIPTION
**Pull request by epszaw**
### Context

fixes #681

Additionally simplifies hermione package test process

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

File: packages/allure-hermione/src/index.ts [hunk 1]
```diff
@@ -236,6 +248,7 @@ const hermioneAllureReporter = (hermione: Hermione, opts: AllureReportOptions) =
     currentTest.addLabel(LabelName.LANGUAGE, "javascript");
     currentTest.addLabel(LabelName.FRAMEWORK, "hermione");
     currentTest.addLabel(LabelName.THREAD, thread);
+    currentTest.addParameter("browser", test.browserId);
```
Comment (vovsemenv) [inline packages/allure-hermione/src/index.ts:251]: do we want to show browserId in report itself? is it id or human-readable name? maybe better to make it hidden?

File: packages/allure-hermione/src/index.ts [hunk 2]
```diff
@@ -220,6 +228,10 @@ const hermioneAllureReporter = (hermione: Hermione, opts: AllureReportOptions) =
     });
   });
   hermione.on(hermione.events.TEST_BEGIN, (test) => {
+    if (!test.sessionId) {
+      throw new Error("Test session hasn't been started correctly! Check the driver availability.");
```
[the remark this answers is not in the document]
Comment (epszaw) [reply packages/allure-hermione/src/index.ts:232]: We do the same in the cucumber reporter. When session isn't initialized the reporter can't work correctly, so the error here looks reasonable from my side. What do you think, @baev?

File: packages/allure-hermione/src/index.ts (hunk 1 above)
Comment (epszaw) [reply packages/allure-hermione/src/index.ts:251]: I think, it would be very useful to know, which browser has been used in the test because we can use many of then in one run at once

Comment (vovsemenv) [reply packages/allure-hermione/src/index.ts:251]: Yes, its really good if browserId is human-readable name. Thats my question

**Review by vovsemenv — APPROVED** [review]
Code looks fine. Only conceptual question in thread above
