### PR TITLE
fix: remove ansi characters in steps statusDetails

### LINKED ISSUE #1076: [v.3.0.0-beta.7][allure-jest][allure-js-commons] The error text in the test step is logged with extra characters
**Describe the bug**
The error text in the test step is logged with extra characters. I suspect that the problem is in the meta information about the text color

**To Reproduce**
1. Create test using **JEST** with steps containing substeps
2. run test with failure 
3. open allure report

```
[2mexpect([22m[31mreceived[39m[2m).[22mtoStrictEqual[2m([22m[32mexpected[39m[2m) // deep equality[22m

Expected: [32m1[39m
Received: [31m2[39m
```

**Expected behavior**
error text without meta information

**Screenshots**
image

### PR DESCRIPTION
**Pull request by todti**
### Context
* Remove ANSI characters in the test steps (fixes #1076 )

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure-js

### CODE REVIEW

File: packages/allure-js-commons/src/sdk/runtime/MessageTestRuntime.ts [hunk 1]
```diff
@@ -184,16 +184,15 @@ export abstract class MessageTestRuntime implements TestRuntime {
...
     } catch (err) {
-      const { message, stack } = err as Error;
+      const details = getMessageAndTraceFromError(err as Error);
 
       await this.sendMessage({
         type: "step_stop",
         data: {
           status: getStatusFromError(err as Error),
           stop: Date.now(),
           statusDetails: {
```
Comment (epszaw) [inline packages/allure-js-commons/src/sdk/runtime/MessageTestRuntime.ts:194]: You can just assign `details` or call the function right in the object:

```
// ...
statusDetails: getMessageAndTraceFromError(err as Error);
// ...
```

**Review by epszaw — APPROVED** [review]
The changes look good. The only one comment I left there is optional to fix

**Review by baev — APPROVED** [review]
