### PR TITLE
Fix playwright path attachments

### LINKED ISSUE #326: [allure-playwright]: Artifacts have fullpath in allure results
Mirroring https://github.com/microsoft/playwright/issues/8079

@baev should I be calling writeAttachment with relative file name? If yes, relative to what?

### PR DESCRIPTION
**Pull request by baev**
#### Context

fixes #326

the change also intruduces new API methods:

```js
AllureRuntime#writeAttachmentFromPath(string, PathLike);
AllureWriter#writeAttachmentFromPath(string, PathLike);
```

#### Checklist
- [x] [Sign Allure CLA][cla]
- [ ] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure2

### CODE REVIEW

File: packages/allure-js-commons/src/writers/FileSystemAllureWriter.ts [hunk 1]
```diff
@@ -22,6 +22,11 @@ export class FileSystemAllureWriter implements AllureWriter {
     writeFileSync(path, content);
   }
 
+  writeAttachmentPath(targetFileName: string, sourceFilePath: PathLike): void {
```
Comment (just-boris) [inline packages/allure-js-commons/src/writers/FileSystemAllureWriter.ts:25]: Reading the method name I expect that it writes the path somewhere, but not the actual file.

How about renaming it to `writeAttachmentFromPath`?

**Review by just-boris — APPROVED** [review]
