### PR TITLE
Fix cypress issues

### LINKED ISSUE #1225: .wallClockStartedAt?.getTime is not a function
**Describe the bug**
When Cypress executes a series of tests, it crashes at the start of the second test with this error:

**Uncaught TypeError: t.wallClockStartedAt?.getTime is not a function**
Image

`test.wallClockStartedAt` is a string (not a Date object) :
Image

and `getTestStartData` from src/browser/utils.ts does not handle it properly 
https://github.com/allure-framework/allure-js/blob/5bbae37a4b434699946fcacf40a9599c35399737/packages/allure-cypress/src/browser/utils.ts#L33

**To Reproduce**
Run multiple tests in a single Cypress run

**Expected behavior**
Cypress run should not crash

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome 128.0.6613.85
 - Cypress 13.13.3
 - allure-cypress 3.0.9

### PR DESCRIPTION
**Pull request by epszaw**
### Context

fixes #1225, #1222

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure-js

### CODE REVIEW

File: packages/allure-cypress/src/browser/commandLog.ts [hunk 1]
```diff
@@ -146,18 +149,31 @@ const getLogProps = (entry: CypressLogEntry) => {
...
   const isAssertionWithMessage = !!maybeGetAssertionLogMessage(entry);
+  const { props, name } = consoleProps();
+
+  // accessing LocalStorage after the page reload can stick the test runner
+  // to avoid the issue, we just need to log the command manually
+  // the problem potentially can happen with other storage related commands, like `clearAllLocalStorage`, `clearAllSessionStorage`, `getAllLocalStorage`, `getAllSessionStorage`, `setLocalStorage`, `setSessionStorage`
+  // but probably, we don't need to silent them all at this moment
+  // the context: https://github.com/allure-framework/allure-js/issues/1222
+  if (["clearLocalStorage"].includes(name)) {
+    return [
```
Comment (delatrie) [inline packages/allure-cypress/src/browser/commandLog.ts:160]: I believe we should just return `[]` here.

**Review by delatrie — CHANGES_REQUESTED** [review]

**Review by delatrie — APPROVED** [review]
