### PR TITLE
Cypress retires handling

### LINKED ISSUE #930: Cypress: Error happened in task "allureReportTest" when the test is skipped in beforeEach()
**Describe the bug**
Error happened in task "allureReportTest" when the test is skipped in beforeEach()

**To Reproduce**
1. Set env var `SKIP_TESTS` to `true`.
2. Run the test which has a logic to conditionally skip the tests in `beforeEach()`
```
context('Conditional run', () => {
  let skip = false;
  before(() => {
    cy.get('div').then(($div) => {
      if (Cypress.env('SKIP_TESTS')) {
        skip = true;
      } else {
        skip = false;
      }
    });
  });

  beforeEach(function () {
    // use regular function here
    if (skip) this.skip();
  });
  it('some test', () => {
    expect(true).to.be.true;
  });
});
```
3. Error occurred as below.
image

**Expected behavior**
Test can be skipped successfully and the result/report is generated.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version 123.0.6312.107

**Smartphone (please complete the following information):**

**Additional context**
 "allure-cypress": "^2.15.1",

### PR DESCRIPTION
**Pull request by epszaw**
- add test to be sure that cypress works skipping tests in hooks
- add retries handling logic for cypress

### Context

fixes #930

#### Checklist
- [x] [Sign Allure CLA][cla]
- [x] Provide unit tests

[cla]: https://cla-assistant.io/accept/allure-framework/allure-js

### CODE REVIEW

File: packages/allure-cypress/src/reporter.ts [hunk 1]
```diff
@@ -170,6 +170,13 @@ export class AllureCypress {
           result.stage = Stage.FINISHED;
           result.status = message.data.status;
 
+          if (message.data.retries > 0) {
+            result.parameters.push({
+              name: "Retries",
```
Comment (baev) [inline packages/allure-cypress/src/reporter.ts:175]:
```suggestion
              name: "Retry",
```

**Review by baev — APPROVED** [review]
