### PR TITLE
fix(playwright): fix historyId field

### LINKED ISSUE #560: [Allure-Playwright] More tests are reported than were actually run
**Describe the bug**
More tests are reported than were actually run. For example, 79 tests were run, of which 73 were successful, 3 failed and only 3
after restarting. The Allure report included 85 tests, of which 73 were successful, 3 broken and 3 failed.

**Expected behavior**
The report should have the same number of tests as when the tests were run (79)

**Screenshots**

**Desktop (please complete the following information):**
 - Playwright Version: 1.29.0, 1.29.1
 - Operating System: Windows, Linux, Mac
 - Node.js version: 18.12.1
 - Browser: Chromium, Firefox, WebKit
 - Allure: 2.0.0-beta.21

### PR DESCRIPTION
**Pull request by vovsemenv**
fixes #560

### CODE REVIEW

File: packages/allure-playwright/src/index.ts [hunk 1]
```diff
@@ -97,8 +97,10 @@ class AllureReporter implements Reporter {
       .join("/");
 
     const fullName = `${relativeFile}#${test.title}`;
+    const fullNameHash = md5(fullName);
     allureTest.fullName = fullName;
-    allureTest.testCaseId = md5(fullName);
+    allureTest.testCaseId = fullNameHash;
+    allureTest.historyId = fullNameHash;
```
Comment (baev) [inline packages/allure-playwright/src/index.ts:103]: Append project

**Review by baev — CHANGES_REQUESTED** [review]

File: packages/allure-playwright/src/index.ts (hunk 1 above)
Comment (vovsemenv) [reply packages/allure-playwright/src/index.ts]: nice catch, thanks

**Review by baev — APPROVED** [review]
